import { StyleSheet } from "react-native"

export const createGlobalStyles = (theme: any) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.colors.background,
            padding: theme.spacing.lg,
        },
        center: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: theme.colors.background,
            padding: theme.spacing.lg,
        },
        screenWithHeader: {
            paddingTop: 180,
            paddingBottom: 40,
        },
        header: {
            fontSize: 26,
            fontFamily: theme.fonts.bold,
            marginBottom: theme.spacing.lg,
            color: theme.colors.text,
        },
        textPrimary: {
            fontSize: 18,
            color: theme.colors.text,
            fontFamily: theme.fonts.regular,
        },
        textSecondary: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            fontFamily: theme.fonts.regular,
        },
        rowText: {
            fontSize: 18,
            marginLeft: 12,
            color: theme.colors.text,
        },
        cancelText: {
            color: theme.colors.textSecondary,
            fontSize: 16,
        },
        card: {
            backgroundColor: theme.colors.white,
            borderRadius: theme.radius.md,
            padding: theme.spacing.md,
            marginBottom: theme.spacing.lg,
            elevation: 2,
        },
        dangerCard: {
            borderWidth: 2,
            borderColor: theme.colors.danger,
            borderRadius: theme.radius.md,
            paddingVertical: theme.spacing.sm,
            marginBottom: theme.spacing.lg,
            backgroundColor: theme.colors.dangerBackground,
        },
        section: {
            marginTop: theme.spacing.lg,
            width: "90%",
            alignSelf: "center",
            backgroundColor: theme.colors.white,
            borderRadius: theme.radius.md,
            padding: theme.spacing.md,
            marginBottom: theme.spacing.lg,
            elevation: 2,
        },
        input: {
            backgroundColor: theme.colors.white,
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.md,
            borderWidth: 1,
            borderColor: "#ccc",
            color: theme.colors.text,
        },
        modalInput: {
            borderWidth: 1,
            borderColor: "#ccc",
            borderRadius: theme.radius.md,
            padding: theme.spacing.md,
            marginBottom: theme.spacing.lg,
            color: theme.colors.text,
            backgroundColor: theme.colors.white,
        },
        buttonPrimary: {
            backgroundColor: theme.colors.primary,
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            alignItems: "center",
            marginTop: theme.spacing.xs,
        },
        buttonPrimaryText: {
            color: theme.colors.white,
            fontSize: 16,
            fontFamily: theme.fonts.bold,
        },
        buttonDanger: {
            backgroundColor: theme.colors.danger,
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            alignItems: "center",
            marginTop: theme.spacing.xs,
        },
        saveBtn: {
            backgroundColor: theme.colors.primary,
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            alignItems: "center",
            marginTop: theme.spacing.xs,
        },
        saveText: {
            color: theme.colors.white,
            fontSize: 16,
            fontFamily: theme.fonts.bold,
        },
        cancelBtn: {
            marginTop: theme.spacing.md,
            alignItems: "center",
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: "rgba(0,0,0,0.4)",
            justifyContent: "center",
            alignItems: "center",
        },
        modalBox: {
            width: "85%",
            backgroundColor: theme.colors.white,
            padding: theme.spacing.lg,
            borderRadius: theme.radius.md,
        },
        modalTitle: {
            fontSize: 20,
            fontFamily: theme.fonts.bold,
            marginBottom: theme.spacing.md,
            color: theme.colors.text,
        },
        modalDescription: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            marginBottom: theme.spacing.sm,
        },
        modalButtons: {
            flexDirection: "row",
            justifyContent: "space-between",
        },
        modalCancel: {
            fontSize: 16,
            color: theme.colors.textSecondary,
        },
        modalSave: {
            fontSize: 16,
            color: theme.colors.primary,
            fontFamily: theme.fonts.bold,
        },
        headerLeft: {
            position: "absolute",
            top: 80,
            left: 40,
        },
        profileName: {
            fontSize: 24,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
        },
        emailName: {
            fontSize: 16,
            color: theme.colors.textSecondary,
            marginTop: 4,
        },
        profileImage: {
            position: "absolute",
            top: 40,
            right: 10,
            width: 120,
            height: 120,
            borderRadius: 32,
            backgroundColor: theme.colors.white,
            borderWidth: 2,
            borderColor: theme.colors.primary,
            justifyContent: "center",
            alignItems: "center",
        },
        dangerSection: {
            borderWidth: 2,
            borderColor: theme.colors.danger,
            borderRadius: theme.radius.md,
            paddingVertical: theme.spacing.sm,
            marginBottom: theme.spacing.lg,
            backgroundColor: theme.colors.dangerBackground,
        },
        row: {
            flexDirection: "row",
            alignItems: "center",
            paddingVertical: theme.spacing.md,
            paddingHorizontal: theme.spacing.md,
        },
        rowBetween: {
            flexDirection: "row",
            justifyContent: "space-between",
            width: "100%",
        },
        rowCenter: {
            flexDirection: "row",
            justifyContent: "space-evenly",
            alignItems: "center",
        },
        column: {
            width: "48%",
        },
        hamburgerButton: {
            width: 56,
            height: 56,
            borderRadius: 28,
            backgroundColor: theme.colors.primary,
            alignItems: "center",
            justifyContent: "center",
            elevation: 8,
            zIndex: 10,
        },
        hamburgerMenu: {
            backgroundColor: theme.colors.white,
            padding: theme.spacing.lg,
            borderTopLeftRadius: theme.radius.md,
            borderTopRightRadius: theme.radius.md,
        },
        hamburgerMenuItem: {
            fontSize: 18,
            paddingVertical: theme.spacing.sm,
            color: theme.colors.text,
            fontFamily: theme.fonts.regular,
        },
        carbChartCard: {
            backgroundColor: theme.colors.white,
            padding: theme.spacing.lg,
            borderRadius: theme.radius.md,
            borderWidth: 1,
            borderColor: "#d0d0d0",
            marginBottom: theme.spacing.lg,
            marginHorizontal: 4,
            shadowColor: "#000",
            shadowOpacity: 0.05,
            shadowRadius: 4,
            elevation: 2,
        },
        carbChartTitle: {
            fontSize: 18,
            fontFamily: theme.fonts.bold,
            textAlign: "center",
            marginBottom: theme.spacing.md,
            color: theme.colors.text,
        },
        carbChartRow: {
            marginBottom: theme.spacing.md,
        },
        carbChartLabel: {
            fontSize: 14,
            marginBottom: 4,
            color: theme.colors.textSecondary,
            fontFamily: theme.fonts.regular,
        },
        carbChartBarBackground: {
            height: 10,
            backgroundColor: theme.colors.textSecondary + "22",
            borderRadius: 5,
            overflow: "hidden",
        },
        carbChartBarFill: {
            height: "100%",
            backgroundColor: theme.colors.primary,
            borderRadius: 5,
            opacity: 0.9,
        },
        carbChartValueRight: {
            fontSize: 12,
            color: theme.colors.textSecondary,
            marginTop: 2,
            textAlign: "right",
            fontFamily: theme.fonts.regular,
        },
        diaryCard: {
            backgroundColor: theme.colors.white,
            borderRadius: theme.radius.lg,
            padding: theme.spacing.lg,
            borderWidth: 1,
            borderColor: "#D1D5DB",
            marginBottom: theme.spacing.lg,
        },
        diaryHeader: {
            backgroundColor: theme.colors.primary + "22",
            paddingVertical: theme.spacing.md,
            paddingHorizontal: theme.spacing.lg,
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.md,
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        diaryHeaderText: {
            fontSize: 16,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
        },
        diaryHeaderCarbs: {
            fontSize: 14,
            color: theme.colors.textSecondary,
        },
        diaryTimeText: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            fontFamily: theme.fonts.medium,
        },
        diaryTapHint: {
            marginTop: 4,
            fontSize: 12,
            color: theme.colors.textSecondary,
        },
        diaryBody: {
            padding: theme.spacing.lg,
        },
        diarySection: {
            marginBottom: theme.spacing.xl,
        },
        diaryFoodRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: theme.spacing.sm,
        },
        diaryFoodName: {
            fontSize: 14,
            color: theme.colors.text,
        },
        diaryFoodCarbs: {
            fontSize: 14,
            color: theme.colors.textSecondary,
        },
        diaryNutrient: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            marginBottom: theme.spacing.xs,
        },
        diaryChartTitle: {
            fontSize: 16,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
            marginBottom: theme.spacing.md,
        },
        diaryBarRow: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: theme.spacing.sm,
        },
        diaryBarLabel: {
            width: 90,
            fontSize: 14,
            color: theme.colors.text,
        },
        diaryBarTrack: {
            flex: 1,
            height: 14,
            backgroundColor: theme.colors.textSecondary + "22",
            borderRadius: 4,
            marginHorizontal: theme.spacing.sm,
        },
        diaryBarFill: {
            height: 14,
            backgroundColor: theme.colors.primary,
            borderRadius: 4,
        },
        diaryActionColumn: {
            justifyContent: "center",
            alignItems: "flex-end",
            marginLeft: theme.spacing.sm,
        },
        diaryEditButton: {
            backgroundColor: theme.colors.primary,
            color: theme.colors.white,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            fontSize: 12,
            overflow: "hidden",
            marginBottom: 4,
        },
        diaryDeleteButton: {
            backgroundColor: theme.colors.danger,
            color: theme.colors.white,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            fontSize: 12,
            overflow: "hidden",
        },
        editFood_optionButton: {
            backgroundColor: theme.colors.primary,
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.md,
            alignItems: "center",
        },
        editFood_optionText: {
            color: theme.colors.white,
            fontFamily: theme.fonts.bold,
            fontSize: 16,
        },
        editFood_inputRow: {
            flexDirection: "row",
            alignItems: "center",
            borderWidth: 1,
            borderColor: "#d0d0d0",
            borderRadius: theme.radius.md,
            paddingHorizontal: theme.spacing.md,
            marginBottom: theme.spacing.md,
        },
        editFood_inputField: {
            flex: 1,
            paddingVertical: theme.spacing.sm,
            fontSize: 16,
            color: theme.colors.text,
        },
        editFood_unitLabel: {
            fontSize: 16,
            color: theme.colors.textSecondary,
            marginLeft: theme.spacing.sm,
            fontFamily: theme.fonts.medium,
        },
        editFood_buttonRow: {
            flexDirection: "row",
            justifyContent: "center",
            gap: theme.spacing.md,
            marginTop: theme.spacing.md,
        },
        editFood_searchInput: {
            backgroundColor: theme.colors.white,
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            borderWidth: 1,
            borderColor: "#d1d5db",
            marginBottom: theme.spacing.md,
            marginTop: theme.spacing.xs,
            fontSize: 16,
            color: theme.colors.text,
        },
        editFood_productItem: {
            padding: theme.spacing.md,
            backgroundColor: theme.colors.white,
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.md,
            borderWidth: 1,
            borderColor: "#e5e7eb",
        },
        editFood_productName: {
            fontSize: 16,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
        },
        editFood_productInfo: {
            fontSize: 14,
            color: theme.colors.textSecondary,
        },
        editFood_productsList: {
            maxHeight: 360,
            marginBottom: theme.spacing.md,
        },
        editFood_amountOverlay: {
            ...StyleSheet.absoluteFillObject,
            backgroundColor: "rgba(0,0,0,0.35)",
            justifyContent: "center",
            alignItems: "center",
            borderRadius: theme.radius.md,
        },
        editFood_amountPopup: {
            width: "85%",
            backgroundColor: theme.colors.white,
            padding: theme.spacing.lg,
            borderRadius: theme.radius.md,
        },
        editFood_productModal: {
            width: "92%",
            maxHeight: "88%",
        },
        foodInput_container: {
            padding: theme.spacing.md,
        },
        foodInput_cameraButton: {
            padding: theme.spacing.sm,
            alignSelf: "flex-start",
            backgroundColor: theme.colors.primary,
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.md,
        },
        foodInput_cameraIcon: {
            fontSize: 24,
            color: theme.colors.white,
        },
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: theme.spacing.sm,
        },
        sectionTitle: {
            fontSize: 18,
            fontFamily: theme.fonts.bold,
            marginBottom: theme.spacing.xs,
            color: theme.colors.text,
        },
        actions: {
            flexDirection: "row",
            alignItems: "center",
        },
        smallButton: {
            backgroundColor: theme.colors.primary,
            width: 40,
            height: 40,
            borderRadius: theme.radius.md,
            justifyContent: "center",
            alignItems: "center",
        },
        listRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginTop: theme.spacing.xs,
        },
        listItem: {
            marginTop: theme.spacing.xs,
            fontSize: 16,
            color: theme.colors.text,
            fontFamily: theme.fonts.regular,
        },
        mealCard: {
            backgroundColor: theme.colors.white,
            borderRadius: theme.radius.md,
            padding: theme.spacing.lg,
            marginBottom: theme.spacing.lg,
            borderWidth: 1,
            borderColor: "#e5e7eb",
            elevation: 2,
        },
        mealCard_header: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        mealCard_headerLeft: {
            flex: 1,
            marginRight: theme.spacing.md,
        },
        mealCard_name: {
            fontSize: 18,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
        },
        mealCard_perServing: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            marginTop: 2,
        },
        mealCard_energyBadge: {
            backgroundColor: theme.colors.primary,
            paddingVertical: 6,
            paddingHorizontal: 12,
            borderRadius: theme.radius.md,
            alignItems: "center",
        },
        mealCard_energyValue: {
            fontSize: 18,
            fontFamily: theme.fonts.bold,
            color: theme.colors.white,
        },
        mealCard_energyUnit: {
            fontSize: 12,
            color: theme.colors.white,
        },
        mealCard_divider: {
            height: 1,
            backgroundColor: "#e5e7eb",
            marginVertical: theme.spacing.md,
        },
        mealCard_nutrients: {
            marginBottom: theme.spacing.lg,
        },
        mealCard_nutrientRow: {
            marginBottom: theme.spacing.md,
        },
        mealCard_nutrientLabelRow: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 4,
        },
        mealCard_nutrientDot: {
            width: 10,
            height: 10,
            borderRadius: 5,
            marginRight: theme.spacing.sm,
        },
        mealCard_nutrientLabel: {
            fontSize: 14,
            color: theme.colors.text,
            flex: 1,
        },
        mealCard_nutrientValue: {
            fontSize: 14,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
        },
        mealCard_nutrientUnit: {
            fontSize: 12,
            color: theme.colors.textSecondary,
        },
        mealCard_barTrack: {
            height: 10,
            backgroundColor: theme.colors.textSecondary + "22",
            borderRadius: 5,
            overflow: "hidden",
        },
        mealCard_barFill: {
            height: "100%",
            borderRadius: 5,
        },
        mealCard_deleteButton: {
            backgroundColor: theme.colors.danger,
            paddingVertical: theme.spacing.sm,
            borderRadius: theme.radius.md,
            alignItems: "center",
        },
        mealCard_deleteText: {
            color: theme.colors.white,
            fontSize: 16,
            fontFamily: theme.fonts.bold,
        },
        todayChart_wrap: {
            backgroundColor: theme.colors.white,
            padding: theme.spacing.lg,
            borderRadius: theme.radius.md,
            borderWidth: 1,
            borderColor: "#e5e7eb",
            marginBottom: theme.spacing.lg,
        },
        todayChart_title: {
            fontSize: 20,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
            marginBottom: theme.spacing.md,
            textAlign: "center",
        },
        todayChart_targetWrap: {
            marginBottom: theme.spacing.lg,
        },
        todayChart_infoText: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            textAlign: "center",
        },
        todayChart_warningText: {
            fontSize: 14,
            color: theme.colors.danger,
            textAlign: "center",
            marginBottom: theme.spacing.sm,
        },
        todayChart_progressTrack: {
            height: 12,
            backgroundColor: theme.colors.textSecondary + "22",
            borderRadius: 6,
            overflow: "hidden",
            marginTop: theme.spacing.sm,
        },
        todayChart_progressFill: {
            height: "100%",
            backgroundColor: theme.colors.primary,
            borderRadius: 6,
        },
        todayChart_errorText: {
            color: theme.colors.danger,
            fontSize: 14,
            textAlign: "center",
            marginBottom: theme.spacing.md,
        },
        todayChart_totalText: {
            fontSize: 16,
            fontFamily: theme.fonts.bold,
            color: theme.colors.text,
            textAlign: "center",
            marginTop: theme.spacing.md,
        },

        todayChart_remainingText: {
            fontSize: 14,
            color: theme.colors.textSecondary,
            textAlign: "center",
            marginTop: theme.spacing.xs,
        },

    })