import { StyleSheet } from "react-native"

export const globalStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#E5F7FD",
        padding: 20,
    },
    screenWithHeader: {
        paddingTop: 180,
        paddingBottom: 40,
    },
    center: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#E5F7FD",
        padding: 20,
    },
    header: {
        fontSize: 26,
        fontWeight: "bold",
        marginBottom: 20,
    },
    textPrimary: {
        fontSize: 18,
        color: "#222",
    },
    textSecondary: {
        fontSize: 14,
        color: "#555",
    },
    card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        elevation: 2,
    },
    dangerCard: {
        borderWidth: 2,
        borderColor: "#d9534f",
        borderRadius: 12,
        paddingVertical: 10,
        marginBottom: 20,
        backgroundColor: "#fff5f5",
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 14,
        paddingHorizontal: 16,
    },
    input: {
        backgroundColor: "#f2f2f2",
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    buttonPrimary: {
        backgroundColor: "#009FE3",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 4,
    },
    buttonPrimaryText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    buttonDanger: {
        backgroundColor: "#d9534f",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.4)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalBox: {
        width: "85%",
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 12,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 12,
    },
    modalDescription: {
        fontSize: 14,
        color: "#555",
        marginBottom: 10,
    },
    overlay: {
        position: "absolute",
        top: 60,
        left: 0,
        right: 0,
        alignItems: "center",
    },
    instructions: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
        backgroundColor: "rgba(0,0,0,0.5)",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    loadingText: {
        color: "#fff",
        fontSize: 16,
        marginTop: 12,
    },
    bottomBar: {
        position: "absolute",
        bottom: 40,
        left: 0,
        right: 0,
        alignItems: "center",
    },
    button: {
        backgroundColor: "#009FE3",
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 10,
    },
    buttonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    section: {
        marginTop: 20,
        width: "90%",
        alignSelf: "center",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 6,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 6,
    },
    actions: {
        flexDirection: "row",
        alignItems: "center",
    },
    smallButton: {
        backgroundColor: "#009FE3",
        width: 40,
        height: 40,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    listRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 6,
    },
    listItem: {
        marginTop: 4,
        fontSize: 16,
    },
    saveBtn: {
        backgroundColor: "#009FE3",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 4,
    },
    saveText: {
        color: "#fff",
        fontSize: 16,
    },
    dangerSection: {
        borderWidth: 2,
        borderColor: "#d9534f",
        borderRadius: 12,
        paddingVertical: 10,
        marginBottom: 20,
        backgroundColor: "#fff5f5",
    },
    rowText: {
        fontSize: 18,
        marginLeft: 12,
        color: "#222",
    },
    cancelBtn: {
        marginTop: 10,
        alignItems: "center",
    },
    cancelText: {
        color: "#555",
        fontSize: 16,
    },
    rowBetween: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
    },
    rowCenter: {
        flexDirection: "row",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    column: {
        width: "48%",
    },
    headerLeft: {
        position: "absolute",
        top: 80,
        left: 40,
    },
    profileName: {
        fontSize: 24,
        fontWeight: "bold",
    },
    emailName: {
        fontSize: 16,
        color: "#555",
        marginTop: 4,
    },
    profileImage: {
        position: "absolute",
        top: 40,
        right: 10,
        width: 120,
        height: 120,
        borderRadius: 32,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: "#009FE3",
        justifyContent: "center",
        alignItems: "center",
    },
    modalButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    modalInput: {
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
    },
    linkButton: {
        backgroundColor: "#009FE3",
        padding: 12,
        borderRadius: 8,
        marginHorizontal: 6,
        color: "#FFFFFF",
    },
    modalCancel: {
        fontSize: 16,
        color: "#888",
    },
    modalSave: {
        fontSize: 16,
        color: "#009FE3",
        fontWeight: "bold",
    },
    warningText: {
        marginTop: 4,
        fontSize: 14,
        color: "#B00020",
    },
    targetModeRow: {
        flexDirection: "row",
        gap: 8,
        marginTop: 8,
        marginBottom: 8,
    },
    modeButton: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#009FE3",
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: "center",
    },
    modeButtonActive: {
        backgroundColor: "#009FE3",
    },
    modeButtonText: {
        color: "#009FE3",
        fontWeight: "700",
    },
    modeButtonTextActive: {
        color: "#FFFFFF",
    },
})