import { StyleSheet } from "react-native"

export const globalStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#E5F7FD",
        padding: 20,
    },
    screenWithHeader: {
        paddingTop: 180,
        paddingBottom: 40,
    },
    center: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#E5F7FD",
        padding: 20,
    },
    header: {
        fontSize: 26,
        fontWeight: "bold",
        marginBottom: 20,
    },
    textPrimary: {
        fontSize: 18,
        color: "#222",
    },
    textSecondary: {
        fontSize: 14,
        color: "#555",
    },
    card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        elevation: 2,
    },
    dangerCard: {
        borderWidth: 2,
        borderColor: "#d9534f",
        borderRadius: 12,
        paddingVertical: 10,
        marginBottom: 20,
        backgroundColor: "#fff5f5",
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 14,
        paddingHorizontal: 16,
    },
    input: {
        backgroundColor: "#f2f2f2",
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    buttonPrimary: {
        backgroundColor: "#009FE3",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 4,
    },
    buttonPrimaryText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    buttonDanger: {
        backgroundColor: "#d9534f",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.4)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalBox: {
        width: "85%",
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 12,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 12,
    },
    modalDescription: {
        fontSize: 14,
        color: "#555",
        marginBottom: 10,
    },
    overlay: {
        position: "absolute",
        top: 60,
        left: 0,
        right: 0,
        alignItems: "center",
    },
    instructions: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
        backgroundColor: "rgba(0,0,0,0.5)",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    loadingText: {
        color: "#fff",
        fontSize: 16,
        marginTop: 12,
    },
    bottomBar: {
        position: "absolute",
        bottom: 40,
        left: 0,
        right: 0,
        alignItems: "center",
    },
    button: {
        backgroundColor: "#009FE3",
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 10,
    },
    buttonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    section: {
        marginTop: 20,
        width: "90%",
        alignSelf: "center",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 6,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 6,
    },
    actions: {
        flexDirection: "row",
        alignItems: "center",
    },
    smallButton: {
        backgroundColor: "#009FE3",
        width: 40,
        height: 40,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    listRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 6,
    },
    listItem: {
        marginTop: 4,
        fontSize: 16,
    },
    saveBtn: {
        backgroundColor: "#009FE3",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 4,
    },
    saveText: {
        color: "#fff",
        fontSize: 16,
    },
    dangerSection: {
        borderWidth: 2,
        borderColor: "#d9534f",
        borderRadius: 12,
        paddingVertical: 10,
        marginBottom: 20,
        backgroundColor: "#fff5f5",
    },
    rowText: {
        fontSize: 18,
        marginLeft: 12,
        color: "#222",
    },
    cancelBtn: {
        marginTop: 10,
        alignItems: "center",
    },
    cancelText: {
        color: "#555",
        fontSize: 16,
    },
    rowBetween: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
    },
    rowCenter: {
        flexDirection: "row",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    column: {
        width: "48%",
    },
    headerLeft: {
        position: "absolute",
        top: 80,
        left: 40,
    },
    profileName: {
        fontSize: 24,
        fontWeight: "bold",
    },
    emailName: {
        fontSize: 16,
        color: "#555",
        marginTop: 4,
    },
    profileImage: {
        position: "absolute",
        top: 40,
        right: 10,
        width: 120,
        height: 120,
        borderRadius: 32,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: "#009FE3",
        justifyContent: "center",
        alignItems: "center",
    },
    modalButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    modalInput: {
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
    },
    linkButton: {
        backgroundColor: "#009FE3",
        padding: 12,
        borderRadius: 8,
        marginHorizontal: 6,
        color: "#FFFFFF",
    },
    modalCancel: {
        fontSize: 16,
        color: "#888",
    },
    modalSave: {
        fontSize: 16,
        color: "#009FE3",
        fontWeight: "bold",
    },
    warningText: {
        marginTop: 4,
        fontSize: 14,
        color: "#B00020",
    },
    targetModeRow: {
        flexDirection: "row",
        gap: 8,
        marginTop: 8,
        marginBottom: 8,
    },
    modeButton: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#009FE3",
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: "center",
    },
    modeButtonActive: {
        backgroundColor: "#009FE3",
    },
    modeButtonText: {
        color: "#009FE3",
        fontWeight: "700",
    },
    modeButtonTextActive: {
        color: "#FFFFFF",
    },
    hamburgerButton: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: "#009FE3",
        alignItems: "center",
        justifyContent: "center",
        elevation: 8,
        zIndex: 10,
    },
    hamburgerMenu: {
        backgroundColor: "#fff",
        padding: 20,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
    },
    hamburgerMenuItem: {
        fontSize: 18,
        paddingVertical: 10,
    },
    carbChartCard: {
        backgroundColor: "#fff",
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#d0d0d0",
        marginBottom: 20,
        marginHorizontal: 4,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    carbChartTitle: {
        fontSize: 18,
        fontWeight: "600",
        textAlign: "center",
        marginBottom: 8,
    },
    carbChartRow: {
        marginBottom: 10,
    },
    carbChartLabel: {
        fontSize: 14,
        marginBottom: 4,
        color: "#333",
    },
    carbChartBarBackground: {
        height: 10,
        backgroundColor: "#e5e7eb",
        borderRadius: 5,
        overflow: "hidden",
    },
    carbChartBarFill: {
        height: "100%",
        backgroundColor: "#4BA3C3",
        borderRadius: 5,
        opacity: 0.9,
    },
    carbChartValueRight: {
        fontSize: 12,
        color: "#444",
        marginTop: 2,
        textAlign: "right",
    },
    diaryCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#D1D5DB",
        overflow: "hidden",
    },
    diaryHeader: {
        backgroundColor: "#4A90E2",
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 12,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    diaryHeaderText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#1F2937",
    },
    diaryHeaderCarbs: {
        fontSize: 14,
        color: "#4B5563",
    },
    diaryTimeText: {
        fontSize: 14,
        color: "#4B5563",
        fontWeight: "500",
    },
    diaryTapHint: {
        marginTop: 4,
        fontSize: 12,
        color: "#6B7280",
    },
    diaryBody: {
        padding: 16,
    },
    diarySection: {
        marginBottom: 24,
    },
    diaryFoodRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    diaryFoodName: {
        fontSize: 14,
        color: "#374151",
    },
    diaryFoodCarbs: {
        fontSize: 14,
        color: "#4B5563",
    },
    diaryNutrient: {
        fontSize: 14,
        color: "#4B5563",
        marginBottom: 4,
    },
    diaryChartTitle: {
        fontSize: 16,
        fontWeight: "600",
        color: "#1F2937",
        marginBottom: 8,
    },
    diaryBarRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    diaryBarTrack: {
        flex: 1,
        height: 14,
        backgroundColor: "#E5E7EB",
        borderRadius: 4,
        marginHorizontal: 8,
    },
    diaryBarFill: {
        height: 14,
        backgroundColor: "#3B82F6",
        borderRadius: 4,
    },
    diaryBarLabel: {
        width: 90,
        fontSize: 14,
        color: "#374151",
    },
    diaryActionColumn: {
        justifyContent: "center",
        alignItems: "flex-end",
        marginLeft: 8,
    },
    diaryEditButton: {
        backgroundColor: "#3B82F6",
        color: "white",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        fontSize: 12,
        overflow: "hidden",
        marginBottom: 4,
    },
    diaryDeleteButton: {
        backgroundColor: "#EF4444",
        color: "white",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        fontSize: 12,
        overflow: "hidden",
    },
    editFood_productModal: {
        width: "92%",
        maxHeight: "88%",
    },
    editFood_optionButton: {
        backgroundColor: "#4BA3C3",
        padding: 12,
        borderRadius: 8,
        marginBottom: 10,
    },
    editFood_optionText: {
        color: "white",
        textAlign: "center",
        fontWeight: "600",
    },
    editFood_productItem: {
        padding: 12,
        backgroundColor: "#fff",
        borderRadius: 8,
        marginBottom: 10,
    },
    editFood_productName: {
        fontSize: 16,
        fontWeight: "bold",
    },
    editFood_productInfo: {
        fontSize: 14,
        color: "gray",
    },
    editFood_productsList: {
        maxHeight: 360,
        marginBottom: 12,
    },
    editFood_amountOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.35)",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 12,
    },
    editFood_amountPopup: {
        width: "85%",
        backgroundColor: "white",
        padding: 20,
        borderRadius: 12,
    },
    editFood_searchInput: {
        backgroundColor: "#fff",
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#d1d5db",
        marginBottom: 12,
        marginTop: 4,
        fontSize: 16,
    },
    editFood_buttonRow: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 14,
        marginTop: 10,
    },
    editFood_modalCancelButton: {
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 4,
    },
    editFood_modalCancelButtonText: {
        color: "gray",
        fontSize: 16,
    },
    editFood_inputRow: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#d0d0d0",
        borderRadius: 8,
        paddingHorizontal: 10,
        marginBottom: 12,
    },
    editFood_inputField: {
        flex: 1,
        paddingVertical: 10,
        fontSize: 16,
    },
    editFood_unitLabel: {
        fontSize: 16,
        color: "#555",
        marginLeft: 8,
        fontWeight: "500",
    },
    foodInput_container: {
        padding: 10,
    },
    foodInput_cameraButton: {
        padding: 8,
        alignSelf: "flex-start",
    },
    foodInput_cameraIcon: {
        fontSize: 24,
    },
    mealCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        marginBottom: 12,
        marginHorizontal: 2,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 8,
        elevation: 3,
    },
    mealCard_header: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        marginBottom: 14,
    },
    mealCard_headerLeft: {
        flex: 1,
        paddingRight: 12,
    },
    mealCard_name: {
        fontSize: 17,
        fontWeight: "700",
        color: "#1A1A2E",
        letterSpacing: -0.3,
        marginBottom: 3,
    },
    mealCard_perServing: {
        fontSize: 12,
        color: "#9B9B9B",
        fontWeight: "500",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    mealCard_energyBadge: {
        backgroundColor: "#FFF3E0",
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        alignItems: "center",
        minWidth: 64,
    },
    mealCard_energyValue: {
        fontSize: 20,
        fontWeight: "800",
        color: "#E67E22",
        letterSpacing: -0.5,
    },
    mealCard_energyUnit: {
        fontSize: 11,
        fontWeight: "600",
        color: "#E67E22",
        opacity: 0.8,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    mealCard_divider: {
        height: 1,
        backgroundColor: "#F0F0F0",
        marginBottom: 14,
    },
    mealCard_nutrients: {
        gap: 10,
        marginBottom: 16,
    },
    mealCard_nutrientRow: {
        gap: 5,
    },
    mealCard_nutrientLabelRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    mealCard_nutrientDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    mealCard_nutrientLabel: {
        flex: 1,
        fontSize: 13,
        fontWeight: "600",
        color: "#555",
        letterSpacing: 0.1,
    },
    mealCard_nutrientValue: {
        fontSize: 14,
        fontWeight: "700",
        color: "#1A1A2E",
    },
    mealCard_nutrientUnit: {
        fontSize: 12,
        fontWeight: "400",
        color: "#9B9B9B",
    },
    mealCard_barTrack: {
        height: 4,
        backgroundColor: "#F0F0F0",
        borderRadius: 2,
        marginLeft: 16,
        overflow: "hidden",
    },
    mealCard_barFill: {
        height: 4,
        borderRadius: 2,
        opacity: 0.75,
    },
    mealCard_deleteButton: {
        borderWidth: 1,
        borderColor: "#FFD6D6",
        borderRadius: 10,
        paddingVertical: 9,
        alignItems: "center",
        backgroundColor: "#FFF5F5",
    },
    mealCard_deleteText: {
        fontSize: 13,
        fontWeight: "600",
        color: "#E74C3C",
        letterSpacing: 0.3,
    },
    todayChart_wrap: {
        marginTop: 0,
        marginBottom: 16,
        alignItems: "center",
        paddingVertical: 0,
        paddingHorizontal: 10,
    },
    todayChart_title: {
        fontSize: 16,
        fontWeight: "700",
        marginBottom: 8,
    },
    todayChart_targetWrap: {
        width: "100%",
        marginBottom: 6,
        paddingHorizontal: 4,
    },
    todayChart_infoText: {
        fontSize: 13,
        fontWeight: "600",
        color: "#B00020",
        marginBottom: 6,
    },
    todayChart_warningText: {
        fontSize: 12,
        color: "#B00020",
        marginBottom: 6,
    },
    todayChart_progressTrack: {
        width: "100%",
        height: 8,
        borderRadius: 999,
        backgroundColor: "#E5E7EB",
        overflow: "hidden",
    },
    todayChart_progressFill: {
        height: "100%",
        backgroundColor: "#009FE3",
    },
    todayChart_totalText: {
        marginTop: 8,
        fontWeight: "600",
    },
    todayChart_remainingText: {
        marginTop: 4,
        fontSize: 14,
        fontWeight: "600",
        color: "#1F2937",
    },
    todayChart_errorText: {
        color: "#B00020",
        textAlign: "center",
    },
    barcode_container: {
        flex: 1,
    },
    barcode_message: {
        fontSize: 16,
        textAlign: "center",
        marginBottom: 20,
        color: "#333",
    },
    diary_dateRow: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 10,
    },
    diary_dateButton: {
        fontSize: 22,
        paddingHorizontal: 20,
        color: "#4A90E2",
    },
    diary_dateText: {
        fontSize: 18,
        fontWeight: "600",
    },
    diary_targetCard: {
        backgroundColor: "#fff",
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#d0d0d0",
        marginBottom: 16,
    },
    diary_targetHeaderRow: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        marginBottom: 8,
    },
    diary_targetTitle: {
        fontSize: 18,
        fontWeight: "600",
    },
    diary_targetLine: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 6,
    },
    diary_summaryCard: {
        backgroundColor: "#fff",
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#d0d0d0",
        marginBottom: 20,
    },
    diary_summaryTitle: {
        fontSize: 18,
        fontWeight: "600",
        marginBottom: 12,
        textAlign: "center",
    },
    diary_summaryGrid: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    diary_summaryColumn: {
        flex: 1,
    },
    diary_summaryItem: {
        fontSize: 14,
        marginBottom: 6,
    },
    diary_mealHeader: {
        fontSize: 20,
        fontWeight: "700",
        marginBottom: 8,
        marginTop: 10,
    },
    diary_mealTypeSummaryCard: {
        backgroundColor: "#fff",
        padding: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#d0d0d0",
        marginBottom: 10,
        marginTop: -4,
        marginHorizontal: 4,
    },
    diary_mealTypeSummaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 2,
    },
    diary_mealTypeSummaryItem: {
        fontSize: 12,
        color: "#444",
    },
    foodSearch_searchRow: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        marginBottom: 10,
    },
    foodSearch_cameraButton: {
        backgroundColor: "#009FE3",
        padding: 10,
        borderRadius: 8,
        marginLeft: 8,
    },
    foodSearch_resultsSection: {
        width: "100%",
        marginTop: 14,
    },
    foodSearch_resultDetail: {
        fontSize: 13,
        color: "#666",
        marginTop: 2,
    },
    foodSearch_detailHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        marginBottom: 6,
    },
    foodSearch_detailCard: {
        borderWidth: 1,
        borderColor: "#009FE3",
        shadowColor: "#009FE3",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    foodSearch_detailHeaderLeft: {
        flex: 1,
        paddingRight: 12,
    },
    foodSearch_detailName: {
        fontSize: 17,
        fontWeight: "700",
        color: "#1A1A2E",
        letterSpacing: -0.3,
        marginBottom: 3,
    },
    foodSearch_detailPerNote: {
        fontSize: 11,
        color: "#9B9B9B",
        fontWeight: "500",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    foodSearch_favoriteButton: {
        width: 32,
        height: 32,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 8,
    },
    foodSearch_favoriteIcon: {
        fontSize: 22,
        color: "#1A1A2E",
    },
    foodSearch_detailDivider: {
        height: 1,
        backgroundColor: "#F0F0F0",
        marginBottom: 14,
    },
    foodSearch_detailNutrientBlock: {
        marginBottom: 10,
    },
    foodSearch_detailNutrientRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 5,
    },
    foodSearch_detailDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    foodSearch_detailNutrientLabel: {
        flex: 1,
        fontSize: 13,
        fontWeight: "600",
        color: "#555",
    },
    foodSearch_detailNutrientValue: {
        fontSize: 14,
        fontWeight: "700",
        color: "#1A1A2E",
    },
    foodSearch_detailNutrientUnit: {
        fontSize: 12,
        fontWeight: "400",
        color: "#9B9B9B",
    },
    foodSearch_detailBarTrack: {
        height: 4,
        backgroundColor: "#F0F0F0",
        borderRadius: 2,
        marginLeft: 16,
        overflow: "hidden",
    },
    foodSearch_detailBarFill: {
        height: 4,
        borderRadius: 2,
        opacity: 0.75,
    },
    mealBuilder_section: {
        marginBottom: 20,
    },
    mealBuilder_label: {
        fontSize: 18,
        marginBottom: 8,
    },
    mealBuilder_mealRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
    },
    mealBuilder_mealButton: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        backgroundColor: "#D0EAF7",
        borderRadius: 8,
    },
    mealBuilder_mealButtonSelected: {
        backgroundColor: "#4BA3C3",
    },
    mealBuilder_mealButtonText: {
        fontSize: 16,
    },
    mealBuilder_mealButtonTextSelected: {
        color: "white",
        fontWeight: "bold",
    },
    mealBuilder_addFoodButton: {
        backgroundColor: "#4BA3C3",
        padding: 12,
        borderRadius: 10,
        alignItems: "center",
        marginBottom: 20,
    },
    mealBuilder_addFoodButtonText: {
        color: "white",
        fontSize: 18,
    },
    mealBuilder_saveButton: {
        backgroundColor: "#009FE3",
        padding: 14,
        borderRadius: 10,
        alignItems: "center",
        marginTop: 20,
    },
    mealBuilder_saveButtonText: {
        color: "white",
        fontSize: 18,
        fontWeight: "bold",
    },
    mealBuilder_modalAddButton: {
        backgroundColor: "#4BA3C3",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginBottom: 10,
    },
    mealBuilder_modalAddButtonText: {
        color: "white",
        fontSize: 16,
    },
    mealBuilder_modalCancelButton: {
        alignItems: "center",
        padding: 10,
    },
    mealBuilder_modalCancelButtonText: {
        color: "gray",
        fontSize: 16,
    },
    mealBuilder_productItem: {
        padding: 12,
        backgroundColor: "#fff",
        borderRadius: 8,
        marginBottom: 10,
    },
    mealBuilder_productName: {
        fontSize: 16,
        fontWeight: "bold",
    },
    mealBuilder_productInfo: {
        fontSize: 14,
        color: "gray",
    },
    med_card: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#D1D5DB",
    },
    med_cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    med_cardTitleRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flex: 1,
    },
    med_cardName: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1F2937",
        flexShrink: 1,
    },
    med_cardActions: {
        flexDirection: "row",
        gap: 4,
    },
    med_iconButton: {
        padding: 6,
    },
    med_infoRow: {
        flexDirection: "row",
        marginBottom: 6,
        gap: 8,
    },
    med_infoLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: "#6B7280",
        width: 52,
    },
    med_infoValue: {
        fontSize: 14,
        color: "#374151",
        flex: 1,
    },
    med_notesRow: {
        marginBottom: 6,
        gap: 4,
    },
    med_notesValue: {
        fontSize: 14,
        color: "#374151",
        fontStyle: "italic",
    },
    med_divider: {
        height: 1,
        backgroundColor: "#E5E7EB",
        marginVertical: 12,
    },
    med_timesLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: "#6B7280",
        marginBottom: 8,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    med_timeSlotRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingVertical: 6,
    },
    med_checkbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: "#009FE3",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
    },
    med_checkboxChecked: {
        backgroundColor: "#009FE3",
        borderColor: "#009FE3",
    },
    med_timeSlotText: {
        fontSize: 15,
        color: "#1F2937",
        fontWeight: "500",
    },
    med_timeSlotTextDone: {
        color: "#9CA3AF",
        textDecorationLine: "line-through",
    },
    med_takenBadge: {
        marginLeft: "auto",
        fontSize: 12,
        color: "#009FE3",
        fontWeight: "600",
        backgroundColor: "#E5F7FD",
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
    },
    med_noTimesText: {
        fontSize: 13,
        color: "#9CA3AF",
        fontStyle: "italic",
        marginTop: 4,
    },
    med_root: {
        flex: 1,
        backgroundColor: "#E5F7FD",
    },
    med_scroll: {
        flex: 1,
    },
    med_scrollContent: {
        padding: 20,
        paddingBottom: 100,
    },
    med_screenHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    med_addButton: {
        backgroundColor: "#009FE3",
        width: 42,
        height: 42,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        elevation: 3,
    },
    med_emptyBox: {
        alignItems: "center",
        marginTop: 60,
        gap: 12,
    },
    med_emptyText: {
        fontSize: 18,
        fontWeight: "600",
        color: "#374151",
    },
    med_emptySubText: {
        fontSize: 14,
        color: "#6B7280",
        textAlign: "center",
    },
    med_modalBox: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        padding: 24,
        width: "94%",
        alignSelf: "center",
        maxWidth: 560,
        maxHeight: "90%",
    },
    med_fieldLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: "#6B7280",
        marginBottom: 6,
        marginTop: 4,
    },
    med_inputMultiline: {
        minHeight: 72,
        textAlignVertical: "top",
    },
    med_timeChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "#E5F7FD",
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 8,
    },
    med_timeChipText: {
        flex: 1,
        fontSize: 15,
        color: "#1F2937",
        fontWeight: "500",
    },
    med_timeRow: {
        flexDirection: "row",
        gap: 10,
        marginBottom: 8,
    },
    med_timeInput: {
        flex: 1,
        marginBottom: 0,
    },
    med_addTimeButton: {
        backgroundColor: "#009FE3",
        width: 46,
        height: 46,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    med_modalActions: {
        flexDirection: "row",
        gap: 12,
        marginTop: 8,
        paddingBottom: 8,
    },
    med_cancelButton: {
        flex: 1,
        padding: 14,
        borderRadius: 10,
        alignItems: "center",
        backgroundColor: "#F3F4F6",
    },
    med_cancelText: {
        fontSize: 15,
        color: "#6B7280",
        fontWeight: "600",
    },
    med_saveButton: {
        flex: 2,
        padding: 14,
        borderRadius: 10,
        alignItems: "center",
        backgroundColor: "#009FE3",
    },
    med_saveText: {
        fontSize: 15,
        color: "#fff",
        fontWeight: "700",
    },
})